CHECKS = [
    ("place(new_board(), 1, 1, 'X')", [[".", ".", "."], [".", "X", "."], [".", ".", "."]]),
    ("place(new_board(), 2, 0, 'O')", [[".", ".", "."], [".", ".", "."], ["O", ".", "."]]),
    (
        "place(place(new_board(), 0, 0, 'X'), 2, 2, 'O')",
        [["X", ".", "."], [".", ".", "."], [".", ".", "O"]],
    ),
    (
        "(untouched := new_board(), place(untouched, 0, 0, 'X'), untouched)[2]",
        [[".", ".", "."], [".", ".", "."], [".", ".", "."]],
    ),
    ("place(new_board(), 3, 0, 'X')", raises(ValueError)),
    ("place(new_board(), 0, 3, 'X')", raises(ValueError)),
    ("place(new_board(), -1, 0, 'X')", raises(ValueError)),
    ("place(new_board(), 0, -1, 'X')", raises(ValueError)),
    ("place(place(new_board(), 1, 1, 'X'), 1, 1, 'O')", raises(ValueError)),
    ("place(place(new_board(), 1, 1, 'X'), 1, 1, 'X')", raises(ValueError)),
    ("place(new_board(), 0, 0, 'Z')", raises(ValueError)),
    ("place(new_board(), 0, 0, 'x')", raises(ValueError)),
    ("winner([['X', 'X', 'X'], ['O', 'O', '.'], ['.', '.', '.']])", "X"),
    ("winner([['O', '.', 'O'], ['X', 'X', 'X'], ['.', '.', '.']])", "X"),
    ("winner([['O', 'O', '.'], ['.', '.', '.'], ['X', 'X', 'X']])", "X"),
    ("winner([['O', 'X', '.'], ['O', 'X', '.'], ['O', '.', '.']])", "O"),
    ("winner([['X', 'O', '.'], ['.', 'O', 'X'], ['.', 'O', '.']])", "O"),
    ("winner([['X', '.', 'O'], ['.', 'X', 'O'], ['.', '.', 'O']])", "O"),
    ("winner([['X', 'O', '.'], ['O', 'X', '.'], ['.', '.', 'X']])", "X"),
    ("winner([['.', 'O', 'X'], ['O', 'X', '.'], ['X', '.', '.']])", "X"),
    ("winner([['X', '.', 'O'], ['X', 'O', '.'], ['O', 'X', '.']])", "O"),
    ("winner(new_board())", None),
    ("winner([['X', 'X', 'O'], ['.', '.', '.'], ['.', '.', '.']])", None),
    ("winner([['.', '.', '.'], ['X', 'O', 'X'], ['O', 'X', 'O']])", None),
    ("winner([['X', 'O', 'X'], ['X', 'O', 'O'], ['O', 'X', 'X']])", None),
    ("result(new_board())", "Game not finished"),
    ("result([['X', 'X', 'X'], ['O', 'O', '.'], ['.', '.', '.']])", "X wins"),
    ("result([['O', '.', 'X'], ['O', 'X', '.'], ['O', '.', 'X']])", "O wins"),
    ("result([['X', 'O', 'X'], ['X', 'O', 'O'], ['O', 'X', 'X']])", "Draw"),
    ("result([['X', 'O', 'X'], ['O', 'X', 'O'], ['O', 'X', 'X']])", "X wins"),
    ("result([['X', 'O', 'X'], ['O', 'X', 'O'], ['O', 'X', '.']])", "Game not finished"),
    ("play('game.txt')", [["O", ".", "X"], ["O", "X", "."], ["O", ".", "X"]]),
    ("play('late.txt')", [["X", "O", "."], ["O", "X", "."], [".", ".", "X"]]),
    ("play('draw.txt')", [["X", "O", "X"], ["X", "O", "O"], ["O", "X", "X"]]),
    ("play('short.txt')", [["O", ".", "O"], [".", "X", "."], [".", ".", "X"]]),
    ("play('taken.txt')", raises(ValueError)),
    ("result(play('late.txt'))", "X wins"),
    ("result(play('draw.txt'))", "Draw"),
    ("result(play('short.txt'))", "Game not finished"),
    ("program()", prints("O . X\nO X .\nO . X\nO wins\n")),
]
