CHECKS = [
    ("clues('crane', 'crane')", "GGGGG"),
    ("clues('crane', 'slate')", "--G-G"),
    ("clues('crane', 'nacre')", "YYYYG"),
    ("clues('hello', 'world')", "-Y-G-"),
    ("clues('a', 'b')", "-"),
    ("clues('', '')", ""),
    ("clues('abc', 'cab')", "YYY"),
    ("clues('apple', 'paper')", "YYGY-"),
    ("clues('sweet', 'speed')", "G-GG-"),
    ("clues('steel', 'sweet')", "G-GGY"),
    ("clues('crane', 'eerie')", "--Y-G"),
    ("clues('abide', 'speed')", "--Y-Y"),
    ("clues('robot', 'floor')", "--YGY"),
    ("clues('abbey', 'babes')", "YYGG-"),
    ("clues('aab', 'aba')", "GYY"),
    ("clues('aabb', 'bbaa')", "YYYY"),
    ("clues('abcd', 'aaaa')", "G---"),
    ("clues('aaaa', 'abaa')", "G-GG"),
    ("clues('crane', 'cranes')", raises(ValueError)),
    ("clues('crane', 'cat')", raises(ValueError)),
    ("clues('cat', 'crane')", raises(ValueError)),
    ("possible_words(['crane', 'trace', 'cat'], 'slate', '--G-G')", ["crane"]),
    ("possible_words(['steel', 'sweet', 'sheep', 'sleep', 'speed'], 'speed', 'G-GG-')", ["steel", "sweet"]),
    ("possible_words(['sweet', 'steel'], 'speed', 'G-GG-')", ["sweet", "steel"]),
    ("possible_words(['crane', 'cranes', 'cat', 'slate'], 'slate', '--G-G')", ["crane"]),
    ("possible_words(['cat', 'dog'], 'slate', '-----')", []),
    ("possible_words(['slate'], 'slate', 'GGGGG')", ["slate"]),
    ("possible_words(['crane', 'trace'], 'slate', 'GGGGG')", []),
    ("possible_words([], 'slate', 'GGGGG')", []),
    ("possible_words(['steel', 'sweet'], 'sweet', 'G-GGY')", ["steel"]),
    (
        "program('2', 'speed G-GG-', 'sweet G-GGY')",
        prints("2\nspeed G-GG-\nsweet G-GGY\nsteel\n"),
    ),
    ("program('1', 'speed G-GG-')", prints("1\nspeed G-GG-\nsteel, sweet\n")),
    ("program('1', 'slate --G-G')", prints("1\nslate --G-G\ncrane, grape, brave\n")),
    ("program('1', 'crane GGGGY')", prints("1\ncrane GGGGY\nNo word fits\n")),
]
