CHECKS = [
    ('money(1250)', '12.50'),
    ('money(5)', '0.05'),
    ('money(0)', '0.00'),
    ('money(100000)', '1000.00'),
    ("(lambda t: (t.add('12.50', 'food', 'lunch'),)[-1])(Tracker())", 1250),
    ("(lambda t: (t.add('3,2', 'transport'),)[-1])(Tracker())", 320),
    ("(lambda t: (t.add('8', 'food'),)[-1])(Tracker())", 800),
    ("(lambda t: (t.add('12.50', 'food'), t.add('3,2', 'transport'), t.add('8', 'food'), t.totals(),)[-1])(Tracker())", [['food', 2050], ['transport', 320]]),
    ("(lambda t: (t.add('1', 'b'), t.add('1', 'a'), t.add('2', 'c'), t.totals(),)[-1])(Tracker())", [['c', 200], ['a', 100], ['b', 100]]),
    ("(lambda t: (t.add('1', 'a'), t.add('2.5', 'b'), t.total(),)[-1])(Tracker())", 350),
    ('(lambda t: (t.total(),)[-1])(Tracker())', 0),
    ('(lambda t: (t.totals(),)[-1])(Tracker())', []),
    ("(lambda t: (t.add('5', 'a', 'x'), t.add('7', 'b'), list(t.undo()),)[-1])(Tracker())", [700, 'b', '']),
    ("(lambda t: (t.add('5', 'a', 'x'), t.undo(), t.total(),)[-1])(Tracker())", 0),
    ("(lambda t: (t.add('5', 'a', 'x'), t.add('7', 'b'), t.undo(), t.totals(),)[-1])(Tracker())", [['a', 500]]),
    ('(lambda ns: (exec("try:\\n    t.add(\'x\', \'food\')\\nexcept ValueError as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'t\': Tracker()})', 'bad amount: x'),
    ('(lambda ns: (exec("try:\\n    t.add(\'\', \'food\')\\nexcept ValueError as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'t\': Tracker()})', 'bad amount: '),
    ('(lambda ns: (exec("try:\\n    t.add(\'0\', \'food\')\\nexcept ValueError as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'t\': Tracker()})', 'amount must be positive'),
    ('(lambda ns: (exec("try:\\n    t.add(\'-5\', \'food\')\\nexcept ValueError as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'t\': Tracker()})', 'amount must be positive'),
    ('(lambda ns: (exec("try:\\n    t.undo()\\nexcept ValueError as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'t\': Tracker()})', 'nothing to undo'),
    ("(lambda t: (t.add('-1', 'x') if False else None, t.entries,)[-1])(Tracker())", []),
    ("program('quit')", prints('> quit\nGoodbye')),
    ("program('add 12.50 Food lunch with ann', 'add 3,2 transport', 'add 8 food', 'report', 'quit')", prints('> add 12.50 Food lunch with ann\nadded 12.50 to food\n> add 3,2 transport\nadded 3.20 to transport\n> add 8 food\nadded 8.00 to food\n> report\nfood 20.50\ntransport 3.20\ntotal 23.70\n> quit\nGoodbye')),
    ("program('add x food', 'add -5 food', 'add 1', 'fly', 'quit')", prints('> add x food\nError: bad amount: x\n> add -5 food\nError: amount must be positive\n> add 1\nError: usage: add AMOUNT CATEGORY [NOTE]\n> fly\nError: unknown command: fly\n> quit\nGoodbye')),
    ("program('add 5 a', 'add 7 b', 'undo', 'undo', 'undo', 'report', 'quit')", prints('> add 5 a\nadded 5.00 to a\n> add 7 b\nadded 7.00 to b\n> undo\nremoved 7.00 from b\n> undo\nremoved 5.00 from a\n> undo\nError: nothing to undo\n> report\nno expenses\n> quit\nGoodbye')),
    ("program('add 12.50 food', 'add 3.2 transport', 'export', 'quit')", prints('> add 12.50 food\nadded 12.50 to food\n> add 3.2 transport\nadded 3.20 to transport\n> export\n{"food": 1250, "transport": 320}\n> quit\nGoodbye')),
    ("program('report', 'REPORT', '', '   ', 'Quit')", prints('> report\nno expenses\n> REPORT\nno expenses\n>\n>\n> Quit\nGoodbye')),
]
