CHECKS = [
    ("round_winner('rock', 'scissors')", "first"),
    ("round_winner('scissors', 'rock')", "second"),
    ("round_winner('paper', 'rock')", "first"),
    ("round_winner('rock', 'paper')", "second"),
    ("round_winner('scissors', 'paper')", "first"),
    ("round_winner('paper', 'scissors')", "second"),
    ("round_winner('paper', 'paper')", "draw"),
    ("round_winner('Rock', 'SCISSORS')", "first"),
    ("round_winner('rock', 'lizard')", raises(ValueError)),
    ("round_winner('spock', 'rock')", raises(ValueError)),
    ("score(['rock', 'paper', 'scissors', 'rock'], ['scissors', 'paper', 'rock', 'rock'])", {"first": 1, "second": 1, "draw": 2}),
    ("score(['rock', 'rock', 'paper'], ['scissors', 'scissors', 'rock'])", {"first": 3, "second": 0, "draw": 0}),
    ("score([], [])", {"first": 0, "second": 0, "draw": 0}),
    ("score(['rock'], ['rock', 'paper'])", raises(ValueError)),
    ("score(['rock', 'lizard'], ['paper', 'paper'])", raises(ValueError)),
    ("program('rock', 'scissors')", prints("rock\nscissors\nPlayer 1 wins\n")),
    ("program('rock', 'paper')", prints("rock\npaper\nPlayer 2 wins\n")),
    ("program('Paper', 'paper')", prints("Paper\npaper\nDraw\n")),
]
