CHECKS = [
    ("parse_message('[2024-03-04 09:12] ann: Good morning @bob')", {'day': '2024-03-04', 'hour': 9, 'author': 'ann', 'text': 'Good morning @bob'}),
    ("parse_message('[2024-03-05 22:41] cy_2: hello: world\\n')", {'day': '2024-03-05', 'hour': 22, 'author': 'cy_2', 'text': 'hello: world'}),
    ("parse_message('[2024-03-05 00:00] bob: x')['hour']", 0),
    ("parse_message('this line is damaged')", None),
    ("parse_message('')", None),
    ("parse_message('[2024-03-05 25:61] eve: this time cannot exist')", None),
    ("parse_message('[2024-03-05 09:12] : no author')", None),
    ("parse_message('2024-03-05 09:12 ann: no brackets')", None),
    ("len(read_messages('chat.log'))", 9),
    ("messages_per_author('chat.log')", [['ann', 3], ['bob', 3], ['cy', 2], ['dee', 1]]),
    ("busiest_day('chat.log')", '2024-03-04'),
    ("mentions('chat.log')", [['bob', 3], ['ann', 2], ['cy', 1], ['dee', 1]]),
    ("top_words('chat.log', 1)", [['great', 6]]),
    ("top_words('chat.log', 4)", [['great', 6], ['lesson', 4], ['lessons', 3], ['about', 2]]),
    ("top_words('chat.log', 8)[4:]", [['classes', 2], ['morning', 2], ['tests', 2], ['done', 1]]),
    ("len(top_words('chat.log', 100))", 27),
    ("top_words('chat.log', 0)", []),
    ("[word for word, count in top_words('chat.log', 100) if word in ('python', 'bob', 'ann', 'errors')]", ['errors', 'python']),
]
