CHECKS = [
    ("Library(load_books('books.json')).available('Dune')", 1),
    ("Library(load_books('books.json')).available('dune')", 1),
    ("Library(load_books('books.json')).available('  EMMA ')", 1),
    ("Library(load_books('books.json')).available('Persuasion')", 1),
    ("Library(load_books('books.json')).available('Ulysses')", 0),
    ("Library(load_books('books.json')).available('Pride and Prejudice')", 2),
    ("Library(load_books('books.json')).find('ulysses')['author']", 'James Joyce'),
    ("(lambda lib: (lib.borrow('dune', 'bob'),)[-1])(Library(load_books('books.json')))", 0),
    ("(lambda lib: (lib.borrow('persuasion', 'bob'),)[-1])(Library(load_books('books.json')))", 0),
    ("(lambda lib: (lib.borrow('emma', 'cy'), lib.available('Emma'),)[-1])(Library(load_books('books.json')))", 0),
    ("(lambda lib: (lib.borrow('pride and prejudice', 'ann'), lib.borrow('Pride and Prejudice', 'bob'),)[-1])(Library(load_books('books.json')))", 0),
    ("(lambda lib: (lib.borrow('pride and prejudice', 'ann'), lib.available('pride and prejudice'),)[-1])(Library(load_books('books.json')))", 1),
    ("(lambda lib: (lib.give_back('dune', 'ann'), lib.available('dune'),)[-1])(Library(load_books('books.json')))", 2),
    ("(lambda lib: (lib.give_back('dune', 'ann'), lib.borrowed_by('ann'),)[-1])(Library(load_books('books.json')))", ['Persuasion']),
    ("(lambda lib: (lib.borrowed_by('ann'),)[-1])(Library(load_books('books.json')))", ['Dune', 'Persuasion']),
    ("(lambda lib: (lib.borrowed_by('nobody'),)[-1])(Library(load_books('books.json')))", []),
    ("(lambda lib: (lib.borrow('emma', 'ann'), lib.borrow('neuromancer', 'ann'), lib.borrowed_by('ann'),)[-1])(Library(load_books('books.json')))", ['Dune', 'Emma', 'Neuromancer', 'Persuasion']),
    ("(lambda lib: (lib.borrow('emma', 'ann'), lib.save('out.json'), [b['borrowed'] for b in load_books('out.json') if b['title'] == 'Emma'],)[-1])(Library(load_books('books.json')))", [['ann']]),
    ("(lambda lib: (lib.save('out.json'), len(load_books('out.json')),)[-1])(Library(load_books('books.json')))", 6),
    ("(lambda lib: (lib.save('out.json'), load_books('out.json') == load_books('books.json'),)[-1])(Library(load_books('books.json')))", True),
    ('(lambda ns: (exec("try:\\n    lib.find(\'zzz\')\\nexcept LibraryError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', 'no such book: zzz'),
    ('(lambda ns: (exec("try:\\n    lib.available(\'Missing Book\')\\nexcept LibraryError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', 'no such book: Missing Book'),
    ('(lambda ns: (exec("try:\\n    lib.borrow(\'Ulysses\', \'ann\')\\nexcept LibraryError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', 'no copies left: Ulysses'),
    ('(lambda ns: (exec("try:\\n    lib.borrow(\'dune\', \'ann\')\\nexcept LibraryError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', 'ann already has Dune'),
    ('(lambda ns: (exec("try:\\n    lib.borrow(\'nothing\', \'ann\')\\nexcept LibraryError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', 'no such book: nothing'),
    ('(lambda ns: (exec("try:\\n    lib.give_back(\'emma\', \'ann\')\\nexcept LibraryError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', "ann doesn't have Emma"),
    ('(lambda ns: (exec("lib.give_back(\'dune\', \'ann\')\\ntry:\\n    lib.give_back(\'dune\', \'ann\')\\nexcept LibraryError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', "ann doesn't have Dune"),
    ('(lambda ns: (exec("try:\\n    lib.give_back(\'zzz\', \'ann\')\\nexcept LibraryError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', 'no such book: zzz'),
    ('(lambda ns: (exec(\'try:\\n    lib.find("zzz")\\nexcept Exception as error:\\n    kind = type(error).__mro__[1].__name__\\n\', globals(), ns), ns[\'kind\'])[1])({\'lib\': Library(load_books(\'books.json\'))})', 'Exception'),
]
