"""Tensors: creating, printing, arithmetic, dtypes, reductions, shapes, indexing and in-place changes."""
CASES = [
    ('create/float2d', 'print(torch.tensor([[1.0, 4.0, 7.0], [2.0, 3.0, 6.0]]))'),
    ('create/int', 'print(torch.tensor([1, 2, 3]))'),
    ('create/bool', 'print(torch.tensor([True, False]))'),
    ('create/mixed int bool', 'print(torch.tensor([True, 2]))'),
    ('create/mixed int float', 'print(torch.tensor([1, 2.5]))'),
    ('create/scalar', 'print(torch.tensor(3.5)); print(torch.tensor(3)); print(torch.tensor(True))'),
    ('create/empty', 'print(torch.tensor([])); print(torch.tensor([]).shape); print(torch.zeros(0, 3)); print(torch.zeros(2, 0, dtype=torch.int64))'),
    ('create/3d', 'print(torch.arange(24).reshape(2, 3, 4)); print(torch.arange(8.).reshape(2, 2, 2))'),
    ('create/neg', 'print(torch.tensor([-1.5, 2.25, -0.125]))'),
    ('create/zeros ones', 'print(torch.zeros(2, 3)); print(torch.ones(3)); print(torch.zeros((2, 2), dtype=torch.int32)); print(torch.ones(2, dtype=torch.float64))'),
    ('create/full', 'print(torch.full((2, 2), 3.5)); print(torch.full((2,), 7)); print(torch.full((2,), True))'),
    ('create/arange', 'print(torch.arange(5)); print(torch.arange(1, 6, 2)); print(torch.arange(0, 1, 0.25)); print(torch.arange(5.)); print(torch.arange(10, 0, -3))'),
    ('create/linspace', 'print(torch.linspace(0, 1, 5)); print(torch.linspace(-1, 1, 4))'),
    ('create/eye', 'print(torch.eye(3)); print(torch.eye(2, 3))'),
    ('create/like', 'x = torch.tensor([[1., 2.], [3., 4.]]); print(torch.zeros_like(x)); print(torch.ones_like(x)); print(torch.full_like(x, 5)); print(torch.zeros_like(torch.tensor([1, 2])))'),
    ('create/numpy f64', 'print(torch.tensor(np.array([[1.0, 2.0], [3.0, 4.0]])))'),
    ('create/numpy f32', 'print(torch.tensor(np.array([1.0, 2.0], dtype=np.float32)))'),
    ('create/numpy int', 'print(torch.tensor(np.array([1, 2, 3], dtype=np.int64)))'),
    ('create/numpy dtype arg', 'print(torch.tensor(np.array([1.0, 2.0]), dtype=torch.float32))'),
    ('create/from_numpy shares', 'a = np.array([1.0, 2.0]); t = torch.from_numpy(a); a[0] = 9; print(t)'),
    ('create/numpy() shares', 't = torch.tensor([1.0, 2.0]); a = t.numpy(); a[0] = 9; print(t); print(a)'),
    ('create/FloatTensor', 'print(torch.FloatTensor([1, 2, 3])); print(torch.FloatTensor(np.array([1.5, 2.5]))); print(torch.FloatTensor(2, 2).shape)'),
    ('create/LongTensor', 'print(torch.LongTensor([1, 2])); print(torch.Tensor([1, 2]))'),
    ('create/dtype arg', 'print(torch.tensor([1, 2], dtype=torch.float32)); print(torch.tensor([1.5, 2.5], dtype=torch.int64)); print(torch.tensor([1., 2.], dtype=torch.float64)); print(torch.tensor([0, 1], dtype=torch.bool))'),
    ('create/requires_grad', 'print(torch.tensor([1., 2.], requires_grad=True)); print(torch.zeros(2, requires_grad=True))'),
    ('create/requires_grad int error', 'torch.tensor([1, 2], requires_grad=True)'),
    ('create/ragged', 'torch.tensor([[1, 2], [3]])'),
    ('create/string', "torch.tensor(['a'])"),
    ('create/negative dim', 'torch.zeros(-1)'),
    ('create/tensor of tensors', 'print(torch.tensor([torch.tensor(1.), torch.tensor(2.)]))'),
    ('create/tensor of tensor copy warn', 't = torch.tensor([1., 2.]); u = torch.tensor(t); print(u)'),
    ('print/sci', 'print(torch.tensor([1e-5, 1.0])); print(torch.tensor([1e10, 1.0])); print(torch.tensor([1e-10, 1e10])); print(torch.tensor([123456789.0, 2.0]))'),
    ('print/int-valued float', 'print(torch.tensor([1., 2., 300.])); print(torch.tensor([1., 2., 3000000.])); print(torch.tensor([1., 2., 30000000000.]))'),
    ('print/mixed decimals', 'print(torch.tensor([0.5, 0.25, 100.123456])); print(torch.tensor([1/3, 2/3, 1.0])); print(torch.tensor([0.00012, 0.5]))'),
    ('print/nan inf', "print(torch.tensor([float('nan'), 1.0, float('inf'), -float('inf')])); print(torch.tensor([float('nan'), float('nan')])); print(torch.tensor([float('inf'), 1.5]))"),
    ('print/zeros', 'print(torch.tensor([0., 0.])); print(torch.tensor([-0., 1.])); print(torch.tensor(0.)); print(torch.tensor([0, 0]))'),
    ('print/long vector', 'print(torch.arange(30.)); print(torch.arange(30) * 1000); print(torch.linspace(0, 1, 25))'),
    ('print/wide matrix', 'print(torch.arange(60.).reshape(3, 20)); print(torch.linspace(0, 1, 40).reshape(2, 20))'),
    ('print/summarized', 'print(torch.arange(2000.)); print(torch.arange(3000.).reshape(1000, 3)); print(torch.zeros(30, 40))'),
    ('print/4d', 'print(torch.arange(16.).reshape(2, 2, 2, 2))'),
    ('print/float64', 'print(torch.tensor([1.5, 2.5], dtype=torch.float64)); print(torch.zeros(2, dtype=torch.float64)); print(torch.tensor([1, 2], dtype=torch.int32)); print(torch.tensor([1, 2], dtype=torch.uint8)); print(torch.tensor([1, 2], dtype=torch.int8)); print(torch.tensor([1.5], dtype=torch.float16))'),
    ('print/requires_grad & dtype long', 'print(torch.tensor([1., 2.], dtype=torch.float64, requires_grad=True)); print(torch.arange(100000.).requires_grad_())'),
    ('print/options precision', 'torch.set_printoptions(precision=2); print(torch.tensor([1.23456, 2.0])); torch.set_printoptions(precision=4)'),
    ('print/options sci', 'torch.set_printoptions(sci_mode=True); print(torch.tensor([1.5, 2.5])); torch.set_printoptions(sci_mode=None)'),
    ('print/options profile', "torch.set_printoptions(profile='full'); print(torch.arange(2000.)[:3]); torch.set_printoptions(profile='default')"),
    ('print/options edgeitems', "torch.set_printoptions(threshold=5, edgeitems=2); print(torch.arange(10.)); print(torch.arange(30.).reshape(6, 5)); torch.set_printoptions(profile='default')"),
    ('attr/shape dtype', 'x = torch.zeros(2, 3); print(x.shape, x.dtype, x.size(), x.size(0), x.size(-1), x.ndim, x.dim(), x.numel(), x.device, x.requires_grad, x.is_leaf)'),
    ('attr/shape slicing', 'x = torch.zeros(2, 3, 4); print(x.shape[1:], x.shape[0], tuple(x.shape), list(x.shape), x.shape == (2, 3, 4), x.shape.numel())'),
    ('attr/dtype reprs', 'print(torch.float32, torch.float, torch.double, torch.long, torch.int, torch.bool, torch.int64 is torch.long, torch.float32.is_floating_point, torch.int64.is_floating_point, torch.float32.itemsize)'),
    ('attr/device', "print(torch.device('cpu'), repr(torch.device('cpu')), torch.device('cuda', 0), repr(torch.device('cuda:1')), torch.zeros(1).device == torch.device('cpu'))"),
    ('attr/item tolist', 'x = torch.tensor([[1., 2.], [3., 4.]]); print(x.tolist(), x[0, 1].item(), x.sum().item(), type(x.sum().item()))'),
    ('attr/item errors', 'torch.tensor([1., 2.]).item()'),
    ('attr/float conv', "t = torch.tensor(2.5); print(float(t), int(t), f'{t:.2f}', f'{t}', bool(torch.tensor(1.)))"),
    ('attr/float conv error', 'float(torch.tensor([1., 2.]))'),
    ('attr/bool error', 'bool(torch.tensor([1., 2.]))'),
    ('attr/format vector error', "print(f'{torch.tensor([1., 2.]):.2f}')"),
    ('attr/len iter', 'x = torch.tensor([[1., 2.], [3., 4.]]); print(len(x)); print(list(x)); print([r.sum() for r in x])'),
    ('attr/len 0d error', 'len(torch.tensor(1.))'),
    ('attr/iter 0d error', 'list(torch.tensor(1.))'),
    ('math/basic', 'x = torch.tensor([[1., 4., 7.], [2., 3., 6.]]); print(10 * (x + 1.0)); print(x - 1); print(x / 2); print(x ** 2); print(-x); print(2 ** x); print(1 / x); print(x // 2); print(x % 3)'),
    ('math/two tensors', 'a = torch.tensor([1., 2., 3.]); b = torch.tensor([4., 5., 6.]); print(a + b, a - b, a * b, a / b, a ** b, a @ b)'),
    ('math/broadcast', 'a = torch.ones(2, 3); b = torch.tensor([1., 2., 3.]); c = torch.tensor([[1.], [2.]]); print(a + b); print(a * c); print(b + c)'),
    ('math/dtype int float', 'i = torch.tensor([1, 2, 3]); print(i + 1, (i + 1).dtype); print(i + 1.5, (i + 1.5).dtype); print(i / 2, (i / 2).dtype); print(i * i, (i * i).dtype); print(i // 2, (i // 2).dtype); print(i ** 2, (i ** 2).dtype); print(i / i)'),
    ('math/dtype promotion', 'f32 = torch.tensor([1., 2.]); f64 = torch.tensor([1., 2.], dtype=torch.float64); i = torch.tensor([1, 2]); b = torch.tensor([True, False]); print((f32 + f64).dtype, (f32 + i).dtype, (i + b).dtype, (b + b).dtype, (f64 + i).dtype, (b * 2).dtype, (b * 1.5).dtype)'),
    ('math/dtype 0d', 'f32 = torch.tensor([1., 2.]); z64 = torch.tensor(1., dtype=torch.float64); i = torch.tensor([1, 2]); print((f32 + z64).dtype, (i + z64).dtype, (i + torch.tensor(1.5)).dtype, (torch.tensor(1) + torch.tensor(2.)).dtype)'),
    ('math/int32', 'a = torch.tensor([1, 2], dtype=torch.int32); print((a + 1).dtype, (a + torch.tensor([1, 2])).dtype, (a * 1.5).dtype)'),
    ('math/bool ops', 'a = torch.tensor([True, False, True]); b = torch.tensor([True, True, False]); print(a & b, a | b, a ^ b, ~a, a + b, a * b, a.sum())'),
    ('math/bool sub error', 'torch.tensor([True]) - torch.tensor([False])'),
    ('math/compare', 'x = torch.tensor([1., 2., 3.]); print(x > 2, x == 2, x != 2, x <= 2, x >= torch.tensor([1., 3., 2.]), x < 2.5)'),
    ('math/compare eq none', 'x = torch.tensor([1., 2.]); print(x == None, x != None)'),
    ('math/unary', 'x = torch.tensor([0.5, 1.0, 2.0]); print(x.exp(), x.log(), x.sqrt(), x.sin(), x.cos(), x.tanh(), x.sigmoid(), x.abs(), x.neg(), x.reciprocal(), x.square())'),
    ('math/unary int', 'i = torch.tensor([1, 4, 9]); print(i.sqrt(), i.exp(), torch.log(i), i.abs(), i.neg(), i.sigmoid(), torch.abs(torch.tensor([-1, 2])))'),
    ('math/round', 'x = torch.tensor([0.5, 1.5, 2.5, -0.5, 1.2345]); print(x.round(), x.floor(), x.ceil(), x.trunc(), x.round(decimals=2), x.sign())'),
    ('math/clamp', 'x = torch.tensor([-2., 0.5, 3.]); print(x.clamp(0, 1), x.clamp(min=0), x.clamp(max=1), torch.clamp(x, -1, 1))'),
    ('math/where', 'x = torch.tensor([-1., 2., -3.]); print(torch.where(x > 0, x, torch.zeros_like(x)), torch.where(x > 0, 1., 0.), torch.where(x > 0, x, 0.))'),
    ('math/maximum', 'a = torch.tensor([1., 5., 3.]); b = torch.tensor([4., 2., 3.]); print(torch.maximum(a, b), torch.minimum(a, b))'),
    ('math/pow variants', 'x = torch.tensor([1., 2., 3.]); print(x ** 0, x ** 0.5, x ** -1, x ** torch.tensor([2., 2., 2.]), torch.pow(x, 3), torch.pow(2, x), torch.pow(x, 2).dtype)'),
    ('math/int neg pow error', 'torch.tensor([1, 2]) ** -1'),
    ('math/relu', 'x = torch.tensor([-1., 0., 2.]); print(x.relu(), torch.relu(x), torch.nn.functional.relu(x))'),
    ('math/floor_divide neg', 'print(torch.tensor([-7., 7.]) // 2, torch.tensor([-7, 7]) // 2, torch.tensor([-7., 7.]) % 3, torch.tensor([-7, 7]) % 3, torch.fmod(torch.tensor([-7., 7.]), 3))'),
    ('math/div mode', "a = torch.tensor([-7., 7.]); print(torch.div(a, 2, rounding_mode='floor'), torch.div(a, 2, rounding_mode='trunc'), torch.div(torch.tensor([-7, 7]), 2, rounding_mode='trunc'))"),
    ('math/div zero', 'print(torch.tensor([1., -1., 0.]) / 0); print(torch.tensor([1, 2]) / 0)'),
    ('math/log zero', 'print(torch.log(torch.tensor([0., -1.]))); print(torch.sqrt(torch.tensor([-1.])))'),
    ('math/alpha', 'a = torch.tensor([1., 2.]); print(torch.add(a, a, alpha=3), a.sub(a, alpha=2))'),
    ('math/numpy operand', 't = torch.tensor([1., 2.]); print(t + np.float32(2), t * np.float64(2)); print((t + np.float64(2)).dtype)'),
    ('math/numpy array operand', 't = torch.tensor([1., 2.]); print(t + np.array([1., 2.]))'),
    ('math/list operand error', 'torch.tensor([1., 2.]) + [1, 2]'),
    ('math/str operand error', "torch.tensor([1., 2.]) + 'a'"),
    ('math/isnan', "x = torch.tensor([1., float('nan'), float('inf')]); print(torch.isnan(x), torch.isinf(x), torch.isfinite(x), torch.nan_to_num(x))"),
    ('math/allclose', 'a = torch.tensor([1., 2.]); b = a + 1e-9; print(torch.allclose(a, b), torch.equal(a, b), torch.equal(a, a.clone()), torch.isclose(a, b))'),
    ('matmul/2d', 'x = torch.tensor([[1., 4., 7.], [2., 3., 6.]]); print(x @ x.T); print(torch.matmul(x, x.T)); print(x.mm(x.T)); print(x.T @ x)'),
    ('matmul/1d', 'a = torch.tensor([1., 2., 3.]); m = torch.ones(3, 2); print(a @ a, a @ m, m.T @ a, torch.dot(a, a), torch.mv(m.T, a))'),
    ('matmul/batched', 'a = torch.arange(12.).reshape(2, 2, 3); b = torch.arange(6.).reshape(3, 2); print(a @ b); print(a @ torch.arange(12.).reshape(2, 3, 2))'),
    ('matmul/shape error', 'torch.ones(3, 4) @ torch.ones(3, 2)'),
    ('matmul/shape error mm', 'torch.ones(3, 4).mm(torch.ones(3, 2))'),
    ('matmul/1d error', 'torch.ones(3) @ torch.ones(4)'),
    ('matmul/dtype error', 'torch.ones(2, 2) @ torch.ones(2, 2, dtype=torch.float64)'),
    ('matmul/int', 'print(torch.tensor([[1, 2], [3, 4]]) @ torch.tensor([[1, 0], [0, 1]]))'),
    ('matmul/outer', 'print(torch.outer(torch.tensor([1., 2.]), torch.tensor([3., 4., 5.])))'),
    ('matmul/mismatches', """for a, b in [((3,), (2, 3)), ((2, 3), (4,)), ((2, 3, 4), (3,)), ((2, 3, 4), (2, 3)), ((3,), (2, 3, 4)), ((3, 4), (2, 3, 5)),
                 ((2, 3, 4), (2, 3, 4)), ((2, 3, 4), (3, 4, 5)), ((2, 3, 4), (4, 3, 2)), ((2, 2, 3), (4,)), ((1, 3), (3, 4, 2))]:
    try:
        print((torch.ones(a) @ torch.ones(b)).shape)
    except RuntimeError as error:
        print(a, b, error)"""),
    ('matmul/mismatches with gradient', """for a, b in [((3, 4), (2, 3, 5)), ((3,), (2, 3, 4)), ((2, 3, 4), (3,)), ((1, 3, 4), (2, 3, 4)), ((2, 3, 4), (1, 5, 5))]:
    for grads in [(True, False), (False, True)]:
        x, y = torch.ones(a, requires_grad=grads[0]), torch.ones(b, requires_grad=grads[1])
        try:
            print((x @ y).shape)
        except RuntimeError as error:
            print(a, b, grads, error)"""),
    ('matmul/grad_fn', """for a, b in [((3,), (3,)), ((2, 3), (3,)), ((3,), (3, 2)), ((2, 3), (3, 2)), ((2, 2, 3), (3, 2)), ((2, 2, 3), (2, 3, 2)), ((3,), (2, 3, 2))]:
    print(a, b, (torch.ones(a, requires_grad=True) @ torch.ones(b)).grad_fn.name())
for a, b in [((3, 4), (2, 4, 5)), ((1, 4), (2, 4, 5)), ((3, 4), (2, 4, 1)), ((4,), (2, 4, 5))]:
    print(a, b, (torch.ones(a, requires_grad=True) @ torch.ones(b)).grad_fn.name())
print(torch.bmm(torch.ones(2, 2, 3, requires_grad=True), torch.ones(2, 3, 4)).grad_fn.name())"""),
    ('matmul/dtype errors', """for fn, a, b in [(torch.dot, (3,), (3,)), (torch.mv, (2, 3), (3,)), (torch.mm, (2, 3), (3, 2)), (torch.bmm, (2, 2, 3), (2, 3, 2)), (torch.matmul, (2, 2, 3), (3,)), (torch.matmul, (2, 2, 3), (2, 3, 2))]:
    for first, second in [(torch.float32, torch.float64), (torch.int64, torch.float32), (torch.int16, torch.float32), (torch.bool, torch.float32), (torch.float32, torch.bool), (torch.bool, torch.bool)]:
        try:
            print(fn(torch.ones(a, dtype=first), torch.ones(b, dtype=second)).dtype)
        except (RuntimeError, NotImplementedError) as error:
            print(fn.__name__, first, second, type(error).__name__, error)"""),
    ('matmul/bmm errors', """for a, b in [((2, 2, 3), (2, 3, 4)), ((2, 2, 3), (3, 3, 4)), ((1, 2, 3), (4, 3, 4)), ((2, 2, 3), (2, 4, 4)), ((2, 3), (2, 3, 4)), ((2, 2, 3), (3, 4))]:
    try:
        print(torch.bmm(torch.ones(a), torch.ones(b)).shape)
    except RuntimeError as error:
        print(a, b, error)"""),
    ('matmul/mv errors', """for a, b in [((2, 3), (3,)), ((2, 3), (4,)), ((2, 3), (3, 1)), ((3,), (3,)), ((2, 2, 3), (3,))]:
    try:
        print(torch.mv(torch.ones(a), torch.ones(b)).shape)
    except RuntimeError as error:
        print(a, b, error)
try:
    torch.mv(torch.tensor(1.), torch.ones(3))
except IndexError as error:
    print(error)"""),
    ('matmul/outer errors', """for a, b in [((3,), (4,)), ((2, 3), (4,)), ((3,), (2, 4))]:
    try:
        print(torch.outer(torch.ones(a), torch.ones(b)).shape)
    except RuntimeError as error:
        print(a, b, error)"""),
    ('T/behaviour', 'x = torch.arange(6.).reshape(2, 3); print(x.T, x.T.shape, x.t().shape, x.transpose(0, 1).shape, x.mT.shape, torch.arange(3.).T)'),
    ('reduce/basic', 'x = torch.tensor([[1., 4., 7.], [2., 3., 6.]]); print(x.sum(), x.mean(), x.sum(dim=0), x.sum(dim=1), x.mean(dim=0), x.mean(dim=1, keepdim=True), x.sum(0, keepdim=True), x.sum(dim=(0, 1)), x.prod(), x.prod(1))'),
    ('reduce/std var', 'x = torch.tensor([[1., 4., 7.], [2., 3., 6.]]); print(x.std(), x.var(), x.std(dim=0), x.std(dim=0, keepdim=True), x.var(dim=1), x.std(unbiased=False), x.std(dim=0, correction=0), x.var(1, unbiased=False))'),
    ('reduce/max min', 'x = torch.tensor([[1., 4., 7.], [2., 3., 6.]]); print(x.max(), x.min(), x.max(dim=0), x.min(dim=1), x.max(1, keepdim=True), torch.max(x, dim=0).values, torch.max(x, 1)[1], x.amax(0), x.amin(1), x.argmax(), x.argmax(dim=1), x.argmin(dim=0))'),
    ('reduce/max tuple unpack', 'x = torch.tensor([[1., 4., 7.], [2., 3., 6.]]); v, i = x.max(dim=1); print(v, i); v, i = torch.max(x, 0); print(v, i)'),
    ('reduce/max ties', 'x = torch.tensor([1., 3., 3., 2.]); print(x.argmax(), x.max(0))'),
    ('reduce/int', 'i = torch.tensor([[1, 2], [3, 4]]); print(i.sum(), i.sum(0), i.sum().dtype, i.prod(), i.max(), i.max(0), i.argmax(), torch.tensor([True, True]).sum(), torch.tensor([True, False]).sum().dtype)'),
    ('reduce/int mean error', 'torch.tensor([1, 2]).mean()'),
    ('reduce/float64', 'x = torch.tensor([1., 2., 3.], dtype=torch.float64); print(x.sum(), x.mean(), x.std())'),
    ('reduce/all any', 'x = torch.tensor([[True, False], [True, True]]); print(x.all(), x.any(), x.all(dim=0), x.any(dim=1), (torch.tensor([1., 2.]) > 0).all())'),
    ('reduce/cumsum', 'x = torch.tensor([[1., 2., 3.], [4., 5., 6.]]); print(x.cumsum(0), x.cumsum(dim=1), torch.cumsum(torch.tensor([1, 2, 3]), 0))'),
    ('reduce/logsumexp', 'x = torch.tensor([[1., 2., 3.], [4., 5., 6.]]); print(torch.logsumexp(x, dim=1), x.logsumexp(0, keepdim=True))'),
    ('reduce/norm', 'x = torch.tensor([3., 4.]); print(x.norm(), torch.norm(x), x.norm(p=1), torch.norm(torch.tensor([[1., 2.], [3., 4.]])))'),
    ('reduce/softmax', 'x = torch.tensor([[1., 2., 3.], [1., 1., 1.]]); print(x.softmax(dim=1), torch.softmax(x, dim=0), x.log_softmax(dim=1), torch.nn.functional.softmax(x, dim=-1))'),
    ('reduce/empty', 'print(torch.tensor([]).sum(), torch.zeros(0, 3).sum(0), torch.tensor([]).mean())'),
    ('reduce/topk', 'x = torch.tensor([[1., 9., 3., 7.], [4., 2., 8., 6.]]); print(torch.topk(x, k=2, dim=1)); v, i = x.topk(3); print(v, i); print(torch.topk(x, 2, largest=False))'),
    ('reduce/sort', 'x = torch.tensor([3., 1., 2.]); print(x.sort()); print(x.sort(descending=True)); print(x.argsort(), torch.sort(torch.tensor([[3., 1.], [2., 5.]]), dim=0))'),
    ('reduce/bad dim', 'torch.zeros(2, 3).sum(dim=2)'),
    ('reduce/bad dim max', 'torch.zeros(2, 3).max(dim=-3)'),
    ('shape/reshape', 'x = torch.arange(6.); print(x.reshape(2, 3), x.reshape(-1, 2), x.view(3, 2), x.reshape((3, 2)), x.view(-1), x.reshape(6, 1).shape, x.flatten(), torch.arange(24).reshape(2, 3, 4).flatten(1).shape)'),
    ('shape/reshape error', 'torch.arange(6.).reshape(4, 2)'),
    ('shape/reshape error neg', 'torch.arange(6.).reshape(4, -1)'),
    ('shape/view error', 'torch.arange(6.).reshape(2, 3).T.view(6)'),
    ('shape/reshape noncontiguous ok', 'print(torch.arange(6.).reshape(2, 3).T.reshape(6))'),
    ('shape/squeeze unsqueeze', 'x = torch.zeros(1, 3, 1); print(x.squeeze().shape, x.squeeze(0).shape, x.squeeze(1).shape, x.unsqueeze(0).shape, x.unsqueeze(-1).shape, torch.zeros(3).unsqueeze(1).shape)'),
    ('shape/permute', 'x = torch.arange(24).reshape(2, 3, 4); print(x.permute(2, 0, 1).shape, x.transpose(0, 2).shape, x.permute(1, 0, 2)[0, 1], x.movedim(0, -1).shape)'),
    ('shape/expand', 'x = torch.tensor([[1.], [2.]]); print(x.expand(2, 3), x.expand(-1, 4).shape, torch.tensor([1., 2.]).expand(3, 2), x.expand_as(torch.zeros(2, 5)).shape, torch.tensor([1, 2]).repeat(2, 2))'),
    ('shape/expand error', 'torch.tensor([1., 2., 3.]).expand(2, 4)'),
    ('shape/cat stack', 'a = torch.tensor([[1., 2.], [3., 4.]]); b = torch.tensor([[5., 6.], [7., 8.]]); print(torch.cat([a, b]), torch.cat([a, b], dim=1), torch.concat([a, b], dim=1), torch.stack([a, b]).shape, torch.stack([a, b], dim=1).shape, torch.stack([a, b], dim=2)[0])'),
    ('shape/cat dtype', 'print(torch.cat([torch.tensor([1, 2]), torch.tensor([3., 4.])]), torch.stack([torch.tensor(1), torch.tensor(2.)]))'),
    ('shape/cat error', 'torch.cat([torch.zeros(2, 3), torch.zeros(2, 4)])'),
    ('shape/cat error dims', 'torch.cat([torch.zeros(2, 3), torch.zeros(3)])'),
    ('shape/stack error', 'torch.stack([torch.zeros(2), torch.zeros(3)])'),
    ('shape/split chunk unbind', 'x = torch.arange(10.); print(x.split(4)); print(x.chunk(3)); print(torch.arange(6.).reshape(2, 3).unbind(0)); print(x.split([2, 8]))'),
    ('shape/flip', 'print(torch.arange(6.).reshape(2, 3).flip(0), torch.arange(5).flip(0))'),
    ('index/basic', 'x = torch.arange(12.).reshape(3, 4); print(x[0], x[1, 2], x[:, 1], x[1:], x[:, :2], x[-1], x[..., 0], x[None].shape, x[:, None].shape, x[::2], x[0, ::2])'),
    ('index/advanced', 'x = torch.arange(12.).reshape(3, 4); print(x[[0, 2]], x[torch.tensor([0, 2])], x[[0, 1], [1, 2]], x[x > 5], x[:, [0, 3]], x[torch.tensor([True, False, True])])'),
    ('index/assign', 'x = torch.zeros(3, 3); x[0] = 1; x[:, 1] = -99; x[2, 2] = 5; print(x); x[x < 0] = 7; print(x); x[[0, 1], [0, 1]] = torch.tensor([8., 9.]); print(x)'),
    ('index/assign dtype', 'x = torch.zeros(3, dtype=torch.int64); x[0] = 2.7; print(x); y = torch.zeros(2); y[0] = torch.tensor(3); print(y)'),
    ('index/shares memory', 'x = torch.arange(6.); v = x[1:4]; v[0] = 100; print(x, v); r = x.reshape(2, 3); r[0, 0] = -1; print(x)'),
    ('index/advanced copies', 'x = torch.arange(6.); c = x[[1, 2]]; c[0] = 100; print(x)'),
    ('index/out of range', 'torch.arange(3.)[5]'),
    ('index/out of range 2d', 'torch.zeros(2, 3)[0, 3]'),
    ('index/too many', 'torch.zeros(2, 3)[0, 0, 0]'),
    ('index/neg step', 'torch.arange(5.)[::-1]'),
    ('index/float index', 'torch.arange(5.)[1.5]'),
    ('index/0d bool', 'x = torch.arange(3.); print(x[torch.tensor(True)].shape, x[torch.tensor(False)].shape)'),
    ('index/item scalar', 'x = torch.arange(6.).reshape(2, 3); print(x[1, 2], type(x[1, 2]), x[1, 2].item(), x[1][2])'),
    ('index/tensor as index int', 'x = torch.arange(5.); i = torch.tensor(2); print(x[i], x[:torch.tensor(3)])'),
    ('inplace/methods', 'x = torch.tensor([1., -2., 3.]); x.add_(1); print(x); x.mul_(2); print(x); x.relu_(); print(x); x.sub_(1).div_(2); print(x); x.zero_(); print(x); x.fill_(3); print(x); x.clamp_(0, 2); print(x); x.neg_(); print(x); x.abs_(); x.pow_(2); x.sqrt_(); x.exp_(); print(x)'),
    ('inplace/operators', 'x = torch.tensor([1., 2.]); y = x; x += 1; x *= 2; x -= 1; x /= 2; print(x, y is x); z = torch.tensor([1, 2]); z += 1; print(z)'),
    ('inplace/dtype error', 'x = torch.tensor([1, 2]); x += 1.5'),
    ('inplace/dtype ok', 'x = torch.tensor([1., 2.]); x += torch.tensor([1, 2]); print(x); x += torch.tensor([1., 2.], dtype=torch.float64); print(x, x.dtype)'),
    ('inplace/shape error', 'x = torch.zeros(2); x += torch.zeros(2, 2)'),
    ('inplace/version', 'x = torch.zeros(3); print(x._version); x.add_(1); print(x._version); x[0] = 1; print(x._version); y = x[1:]; y.zero_(); print(x._version, y._version)'),
    ('inplace/copy', 'x = torch.zeros(3); x.copy_(torch.tensor([1, 2, 3])); print(x); x.copy_(torch.tensor(5.)); print(x)'),
    ('inplace/masked_fill', 'x = torch.tensor([1., 2., 3.]); print(x.masked_fill(x > 1, 0.)); x.masked_fill_(x < 2, -1.); print(x)'),
    ('inplace/leaf error', 'x = torch.tensor([1., 2.], requires_grad=True); x += 1'),
    ('inplace/leaf error add_', 'x = torch.tensor([1., 2.], requires_grad=True); x.add_(1)'),
    ('inplace/leaf error setitem', 'x = torch.tensor([1., 2.], requires_grad=True); x[0] = 5'),
    ('inplace/leaf ok under no_grad', 'x = torch.tensor([1., 2.], requires_grad=True)\nwith torch.no_grad():\n    x += 1\n    x[0] = 9\nprint(x, x.requires_grad, x.is_leaf, x.grad_fn)'),
    ('inplace/data attr', 'x = torch.tensor([1., 2.], requires_grad=True); x.data += 1; print(x); x.data.zero_(); print(x); print(x.data.requires_grad, x.detach().requires_grad)'),
    ('inplace/detach shares', 'x = torch.tensor([1., 2.]); d = x.detach(); d[0] = 9; print(x)'),
    ('inplace/clone independent', 'x = torch.tensor([1., 2.]); c = x.clone(); c[0] = 9; print(x, c)'),
    ('convert/to dtype', "x = torch.tensor([1.5, 2.5]); print(x.to(torch.int64), x.int(), x.long(), x.double(), x.half(), x.bool(), x.float() is x, x.to(torch.float32) is x, x.to('cpu') is x, x.to(dtype=torch.float64), x.type(torch.int32))"),
    ('convert/to other', "x = torch.tensor([1.5, 2.5]); y = torch.tensor([1], dtype=torch.float64); print(x.to(y).dtype, x.type_as(y).dtype, x.cpu() is x, x.to('cpu', torch.float64).dtype)"),
    ('convert/type str', "x = torch.tensor([1.5]); print(x.type(), torch.tensor([1]).type(), x.type('torch.LongTensor'))"),
    ('convert/device kw error', "torch.zeros(2, device='cuda')"),
    ('convert/numpy grad error', 'torch.tensor([1.], requires_grad=True).numpy()'),
    ('convert/np array conv', 't = torch.tensor([1., 2.]); print(np.array(t), np.asarray(t) + 1, np.float32(2) * t)'),
    ('convert/np mul order', 't = torch.tensor([1., 2.]); r = np.float64(2) * t; print(type(r).__name__, r)'),
    ('convert/isinstance', 'print(isinstance(torch.zeros(1), torch.Tensor), isinstance(torch.zeros(1), torch.FloatTensor), isinstance(torch.zeros(1, dtype=torch.long), torch.FloatTensor), torch.is_tensor(torch.zeros(1)), torch.is_tensor(3))'),
]
