CHECKS = [
    ('parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}]\')', [{'title': 'Dune', 'author': 'Frank Herbert', 'copies': 2, 'borrowed': ['ann']}]),
    ("parse_books('[]')", []),
    ('len(parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}, {"title": "Dune", "author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}, {"title": "Dune", "author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}]\'))', 3),
    ("len(load_books('books.json'))", 6),
    ("load_books('books.json')[3]['borrowed']", ['ann', 'cy']),
    ("[book['title'] for book in load_books('books.json')][:3]", ['Dune', 'Emma', 'Ulysses']),
    ("parse_books('not json')", raises(ValueError)),
    ("parse_books('{}')", raises(ValueError)),
    ("parse_books('[1]')", raises(ValueError)),
    ('parse_books(\'[{"author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "Dune", "copies": 2, "borrowed": ["ann"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "borrowed": ["ann"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "copies": 2}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "", "author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": 5, "author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "copies": -1, "borrowed": ["ann"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "copies": true, "borrowed": ["ann"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "copies": "2", "borrowed": ["ann"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "copies": 2, "borrowed": ["a", "b", "c"]}]\')', raises(ValueError)),
    ('parse_books(\'[{"title": "Dune", "author": "Frank Herbert", "copies": 2, "borrowed": "ann"}]\')', raises(ValueError)),
    ('(lambda ns: (exec("try:\\n    parse_books(\'not json\')\\nexcept ValueError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({})', 'not valid JSON'),
    ('(lambda ns: (exec("try:\\n    parse_books(\'{}\')\\nexcept ValueError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({})', 'expected a list of books'),
    ('(lambda ns: (exec("try:\\n    parse_books(\'[1]\')\\nexcept ValueError as error:\\n    message = str(error)\\n", globals(), ns), ns[\'message\'])[1])({})', 'book 1: expected an object'),
    ('(lambda ns: (exec(\'try:\\n    parse_books(\\\'[{"title": "Dune", "copies": 2, "borrowed": ["ann"]}]\\\')\\nexcept ValueError as error:\\n    message = str(error)\\n\', globals(), ns), ns[\'message\'])[1])({})', 'book 1: missing author'),
    ('(lambda ns: (exec(\'try:\\n    parse_books(\\\'[{"title": "Dune", "author": "Frank Herbert", "copies": 2}]\\\')\\nexcept ValueError as error:\\n    message = str(error)\\n\', globals(), ns), ns[\'message\'])[1])({})', 'book 1: missing borrowed'),
    ('(lambda ns: (exec(\'try:\\n    parse_books(\\\'[{"title": "", "author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}]\\\')\\nexcept ValueError as error:\\n    message = str(error)\\n\', globals(), ns), ns[\'message\'])[1])({})', 'book 1: bad title'),
    ('(lambda ns: (exec(\'try:\\n    parse_books(\\\'[{"title": "Dune", "author": "Frank Herbert", "copies": -1, "borrowed": ["ann"]}]\\\')\\nexcept ValueError as error:\\n    message = str(error)\\n\', globals(), ns), ns[\'message\'])[1])({})', 'book 1: bad copies'),
    ('(lambda ns: (exec(\'try:\\n    parse_books(\\\'[{"title": "Dune", "author": "Frank Herbert", "copies": true, "borrowed": ["ann"]}]\\\')\\nexcept ValueError as error:\\n    message = str(error)\\n\', globals(), ns), ns[\'message\'])[1])({})', 'book 1: bad copies'),
    ('(lambda ns: (exec(\'try:\\n    parse_books(\\\'[{"title": "Dune", "author": "Frank Herbert", "copies": 2, "borrowed": ["a", "b", "c"]}]\\\')\\nexcept ValueError as error:\\n    message = str(error)\\n\', globals(), ns), ns[\'message\'])[1])({})', 'book 1: more borrowed than copies'),
    ('(lambda ns: (exec(\'try:\\n    parse_books(\\\'[{"title": "Dune", "author": "Frank Herbert", "copies": 2, "borrowed": ["ann"]}, {"title": "x"}]\\\')\\nexcept ValueError as error:\\n    message = str(error)\\n\', globals(), ns), ns[\'message\'])[1])({})', 'book 2: missing author'),
]
