CHECKS = [
    ("Basket().total()", 0),
    ("Basket().add('tea', 3).total()", 3),
    ("Basket().add('tea', 3).add('cake', 4, 2).total()", 11),
    ("Basket().add('tea', 2.5, 4).total()", 10),
    ("Basket().count()", 0),
    ("Basket().add('tea', 3).add('cake', 4, 2).count()", 3),
    ("repr(Basket())", "Basket(items=0, total=0)"),
    ("repr(Basket().add('tea', 3).add('cake', 4, 2))", "Basket(items=3, total=11)"),
    ("Basket().add('tea', 3, 0)", raises(ValueError)),
    ("Basket().add('tea', 3).add('cake', 4, -1)", raises(ValueError)),
    ("DiscountBasket(50).total()", 0),
    ("DiscountBasket(50).add('tea', 3).add('cake', 4, 2).total()", 5.5),
    ("DiscountBasket(0).add('tea', 3).add('cake', 4, 2).total()", 11),
    ("DiscountBasket(10).add('tea', 5, 2).total()", 9),
    ("DiscountBasket(100).add('tea', 5).total()", 0),
    ("DiscountBasket(10).add('tea', 5, 2).count()", 2),
    ("isinstance(DiscountBasket(10), Basket)", True),
    ("DiscountBasket(10).add('tea', 5, 0)", raises(ValueError)),
]
