CHECKS = [
    ("best_version('>=2.0,<3', ['1.26.4', '2.0.2', '2.4.6', '3.0.0'])", '2.4.6'),
    ("best_version('', ['2.9.0', '2.10.1', '2.14.1'])", '2.14.1'),
    ("best_version('<2.10', ['2.9.0', '2.10.1', '2.14.1'])", '2.9.0'),
    ("best_version('>=4', ['2.9.0', '2.10.1'])", None),
    ("best_version('==2.10', ['2.10.0', '2.9'])", '2.10.0'),
    ("best_version('!=2.14.1', ['2.9.0', '2.10.1', '2.14.1'])", '2.10.1'),
    ("best_version('>1.9', ['1.9', '1.10', '1.2'])", '1.10'),
    ("best_version('>=1', [])", None),
    ("best_version(' >= 2.0 , < 3 ', ['2.5', '3.1'])", '2.5'),
    ('resolve(\'[project]\\nname = "x"\\ndependencies = ["numpy>=2.0,<3", "torch"]\\n\', AVAILABLE)', {'numpy': '2.4.6', 'torch': '2.14.1'}),
    ('resolve(\'[project]\\nname = "x"\\ndependencies = ["NumPy >= 2.0"]\\n\', AVAILABLE)', {'numpy': '3.0.0'}),
    ('resolve(\'[project]\\nname = "x"\\ndependencies = ["torch<2.10", "numpy==1.26.4"]\\n\', AVAILABLE)', {'torch': '2.9.0', 'numpy': '1.26.4'}),
    ('resolve(\'[project]\\nname = "x"\\n\', AVAILABLE)', {}),
    ('resolve(\'[project]\\nname = "x"\\ndependencies = []\\n\', AVAILABLE)', {}),
    ('(lambda ns: (exec(\'try:\\n    resolve(\\\'[project]\\\\nname = "x"\\\\ndependencies = ["scipy"]\\\\n\\\', AVAILABLE)\\nexcept LookupError as error:\\n    message = str(error)\\nelse:\\n    message = \\\'no error\\\'\\n\', globals(), ns), ns[\'message\'])[1])({})', 'unknown package: scipy'),
    ('(lambda ns: (exec(\'try:\\n    resolve(\\\'[project]\\\\nname = "x"\\\\ndependencies = ["numpy>=4"]\\\\n\\\', AVAILABLE)\\nexcept LookupError as error:\\n    message = str(error)\\nelse:\\n    message = \\\'no error\\\'\\n\', globals(), ns), ns[\'message\'])[1])({})', 'no version of numpy fits >=4'),
    ('(lambda ns: (exec(\'try:\\n    resolve(\\\'[project]\\\\nname = "x"\\\\ndependencies = ["torch <2.9"]\\\\n\\\', AVAILABLE)\\nexcept LookupError as error:\\n    message = str(error)\\nelse:\\n    message = \\\'no error\\\'\\n\', globals(), ns), ns[\'message\'])[1])({})', 'no version of torch fits <2.9'),
    ('(lambda ns: (exec(\'try:\\n    resolve(\\\'[project]\\\\nname = "x"\\\\ndependencies = ["numpy", "scipy"]\\\\n\\\', AVAILABLE)\\nexcept LookupError as error:\\n    message = str(error)\\nelse:\\n    message = \\\'no error\\\'\\n\', globals(), ns), ns[\'message\'])[1])({})', 'unknown package: scipy'),
    ('resolve(\'[project]\\nname = "x"\\ndependencies = ["numpy>=2.0", "torch"]\\n\', {\'numpy\': [\'2.1\'], \'torch\': [\'0.1\']})', {'numpy': '2.1', 'torch': '0.1'}),
    ("AVAILABLE['numpy'][-1]", '3.0.0'),
]
