CHECKS = [
    ("(lambda a, b: (a.deposit(50),)[-1])(Account('ann', 100), Account('bob', 20))", 150),
    ("(lambda a, b: (a.withdraw(30),)[-1])(Account('ann', 100), Account('bob', 20))", 70),
    ("(lambda a, b: (a.deposit(5), a.withdraw(10), [a.balance, a.history],)[-1])(Account('ann', 100), Account('bob', 20))", [95, ['deposit 5', 'withdraw 10']]),
    ("(lambda a, b: (repr(a),)[-1])(Account('ann', 100), Account('bob', 20))", "Account('ann', 100)"),
    ("(lambda a, b: (a.history,)[-1])(Account('ann', 100), Account('bob', 20))", []),
    ("(lambda a, b: (a.withdraw(100),)[-1])(Account('ann', 100), Account('bob', 20))", 0),
    ("Account('cy').balance", 0),
    ('(lambda ns: (exec("try:\\n    a.withdraw(101)\\nexcept InsufficientFunds as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'a\': Account(\'ann\', 100), \'b\': Account(\'bob\', 20)})', 'ann has 100, needs 101'),
    ('(lambda ns: (exec("try:\\n    a.withdraw(0)\\nexcept ValueError as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'a\': Account(\'ann\', 100), \'b\': Account(\'bob\', 20)})', 'amount must be positive'),
    ('(lambda ns: (exec("try:\\n    a.deposit(-5)\\nexcept ValueError as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'a\': Account(\'ann\', 100), \'b\': Account(\'bob\', 20)})', 'amount must be positive'),
    ('(lambda ns: (exec("a.frozen = True\\ntry:\\n    a.deposit(5)\\nexcept AccountFrozen as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'a\': Account(\'ann\', 100), \'b\': Account(\'bob\', 20)})', "ann's account is frozen"),
    ('(lambda ns: (exec("a.frozen = True\\ntry:\\n    a.withdraw(5)\\nexcept AccountFrozen as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'a\': Account(\'ann\', 100), \'b\': Account(\'bob\', 20)})', "ann's account is frozen"),
    ("(lambda a, b: (a.withdraw(500) if False else None, [a.balance, a.history],)[-1])(Account('ann', 100), Account('bob', 20))", [100, []]),
    ("(lambda a, b: (transfer(a, b, 30), [a.balance, b.balance],)[-1])(Account('ann', 100), Account('bob', 20))", [70, 50]),
    ("(lambda a, b: (transfer(a, b, 30), [a.history, b.history],)[-1])(Account('ann', 100), Account('bob', 20))", [['withdraw 30'], ['deposit 30']]),
    ('(lambda ns: (exec("transfer(a, b, 30)\\ntry:\\n    transfer(a, b, 500)\\nexcept InsufficientFunds as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'a\': Account(\'ann\', 100), \'b\': Account(\'bob\', 20)})', 'ann has 70, needs 500'),
    ('(lambda ns: (exec("b.frozen = True\\ntry:\\n    transfer(a, b, 30)\\nexcept AccountFrozen as error:\\n    message = str(error)\\nelse:\\n    message = \'no error\'\\n", globals(), ns), ns[\'message\'])[1])({\'a\': Account(\'ann\', 100), \'b\': Account(\'bob\', 20)})', "bob's account is frozen"),
    ("(lambda ns: (exec('b.frozen = True\\ntry:\\n    transfer(a, b, 30)\\nexcept AccountFrozen:\\n    pass\\nstate = [a.balance, b.balance, a.history, b.history]\\n', globals(), ns), ns['state'])[1])({'a': Account('ann', 100), 'b': Account('bob', 20)})", [100, 20, [], []]),
    ("(lambda ns: (exec('try:\\n    transfer(a, b, 500)\\nexcept InsufficientFunds:\\n    pass\\nstate = [a.balance, b.balance, a.history, b.history]\\n', globals(), ns), ns['state'])[1])({'a': Account('ann', 100), 'b': Account('bob', 20)})", [100, 20, [], []]),
    ("(lambda ns: (exec('try:\\n    transfer(a, b, -5)\\nexcept ValueError:\\n    pass\\nstate = [a.balance, b.balance, a.history, b.history]\\n', globals(), ns), ns['state'])[1])({'a': Account('ann', 100), 'b': Account('bob', 20)})", [100, 20, [], []]),
    ("(lambda ns: (exec('a.frozen = True\\ntry:\\n    transfer(a, b, 5)\\nexcept AccountFrozen:\\n    pass\\nstate = [a.balance, b.balance, a.history, b.history]\\n', globals(), ns), ns['state'])[1])({'a': Account('ann', 100), 'b': Account('bob', 20)})", [100, 20, [], []]),
    ("(lambda a, b: (transfer(a, b, 100), [a.balance, b.balance],)[-1])(Account('ann', 100), Account('bob', 20))", [0, 120]),
    ('issubclass(InsufficientFunds, Exception) and issubclass(AccountFrozen, Exception)', True),
]
